import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {MatPaginatorModule} from '@angular/material/paginator';
import {MatButtonModule,
  MatCheckboxModule,
  MatDialogModule,
  MatDatepickerModule,
  MatFormField,
  MatInputModule,
  MatNativeDateModule,
  MatFormFieldModule,
  MatTabGroup,
  MatProgressSpinnerModule,
  MatTabLabel,
  MatTab,
  MatTabsModule,
  MatCardModule,
  MatListModule,
  MatToolbarModule,
  MatTableModule,
  MatGridListModule,
  MatGridTile,
  MatSelectModule,
  MatMenuModule,
  MatToolbarRow,
  MatIconModule,
  MatChipsModule,
  MatTreeModule,
  MatSortModule,
  MatSidenavModule,
  MatStepperModule,
  MatProgressBarModule,
  MatRadioModule
} from '@angular/material';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MatTabBase } from '@angular/material/tabs/typings/tab';
@NgModule({
  declarations: [ ],
  imports: [
    CommonModule,
    MatButtonModule,
    MatCheckboxModule,
    MatDialogModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatNativeDateModule,
    MatInputModule,
    BrowserAnimationsModule,
    MatProgressSpinnerModule,
    MatButtonModule,
    MatCardModule,
    MatInputModule,
    MatListModule,
    MatToolbarModule,
    MatPaginatorModule,
    MatTableModule,
    MatGridListModule,
    MatTabsModule,
    MatSelectModule,
    MatMenuModule,
    MatIconModule,
    MatChipsModule,
    MatTreeModule,
    MatSortModule,
    MatSidenavModule,
    MatStepperModule,
    MatProgressBarModule,
    MatRadioModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatDialogModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatNativeDateModule,
    MatInputModule,
    BrowserAnimationsModule,
    MatProgressSpinnerModule,
    MatButtonModule,
    MatCardModule,
    MatInputModule,
    MatListModule,
    MatToolbarModule,
    MatPaginatorModule,
    MatTableModule,
    MatGridListModule,
    MatGridTile,
    MatTabsModule,
    MatSelectModule,
    MatMenuModule,
    MatIconModule,
    MatChipsModule,
    MatTreeModule,
    MatSortModule,
    MatSidenavModule,
    MatStepperModule,
    MatProgressBarModule,
    MatRadioModule
  ],
  providers: [ MatDatepickerModule ]
})
export class MaterialModule { }
