export class Authorize {
    // reportId:string;
    // reportName:string;
    // reportType:string;
    // reportMessage:string;
    // makerId:string;
    // makerDateStamp:Date;
    // checkerId:string;
    // checkerDateStamp:Date;
    // authStatus:string;
    userRef : string;
	  userId: string  ;
	  userName: string  ;
	  userType: string  ;
	  roleId: string  ;
	  emailId: string  ;
	  brnCode: string  ;
	  mobileNo: string  ;
	  activeStatus: string  ;
	 sendNotification: boolean  ;
	 phoneNumber: number  ;
	  versionNo: number  ;
	  userPwd: string  ;
	  newPwdFlg: string  ;
	  failLgnCounter: number  ;
	  initBrn: string  ;
	  lastLgnTime: string  ;
	  lastFailLgnTime: string  ;
	  loggerSwitch: string  ;
	  pwdNoExpiry: number  ;
	  pwdExpiryDays: number  ;
	  failedAttempts: number  ;
      pwdChangeDate: Date  ;
      buttonupdate?:boolean;
  password: any;
  logoutTime: any;
  responeMsg:string;
  status: string;
    status2?:boolean;
    button?:boolean;
    // file:File;
}

