export class ExtsysClass {
    id: number;
    action: string;
    commChannel: string;
    createdAt: string;
    creatorDtStamp: Date;
    creatorId: string;
    destination: string;
    destinationTag: string;
    dtdFile: string;
    errDirectoryName: string;
    errQueueName: string;
    errSchemaName: string;
    errXsltName: string;
    extSysCode: string;
    extSysName: string;
    extSysTag: string;
    formatType: string;
    isDestNode: string;
    isExtSysNode: string;
    isModuleNode: string;
    isProcessNode: string;
    isServiceNode: string;
    latestAmendNo: string;
    messageType: string;
    moduleCode: string;
    moduleTag: string;
    msgDuplication: string;
    processCode: string;
    processTag: string;
    recordStatus: string;
    reqDirectoryName: string;
    reqQueueName: string;
    reqSchemaName: string;
    reqXsltName: string;
    requestTag: string;
    respDirectoryName: string;
    respQueueName: string;
    respSchemaName: string;
    respXsltName: string;
    responseTag: string;
    serviceCode: string;
    serviceTag: string;
    updatedAt: string;
    verifiedEver: string;
    versionNo:number;
    verifierDtStamp: string;
    verifierId: string;
    xsdFile: File;
   // dtdFile: File;
    authStatus: string;
    updatedBy: string;
    fristTimeAuth: string;
    
    
}
